-- -- SCRIPT PARA CREACIÓN DE TABLAS INICIALES

-- 1. Tabla de clientes
CREATE TABLE Clientes (
    ClienteID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nombre NVARCHAR2(100) NOT NULL,
    Telefono NVARCHAR2(20),
    Correo NVARCHAR2(100),
    FechaRegistro DATE DEFAULT SYSDATE
);

-- 2. Tabla de empleados
CREATE TABLE Empleados (
    EmpleadoID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nombre NVARCHAR2(100) NOT NULL,
    Cargo NVARCHAR2(50),
    FechaContratacion DATE DEFAULT SYSDATE
);

-- 3. Tabla de usuarios (ligados a empleados)
CREATE TABLE Usuarios (
    UsuarioID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    EmpleadoID NUMBER REFERENCES Empleados(EmpleadoID),
    NombreUsuario NVARCHAR2(50) NOT NULL,
    Contrasena NVARCHAR2(100) NOT NULL,
    Rol NVARCHAR2(20)
);

-- 4. Tabla de categorías
CREATE TABLE Categorias (
    CategoriaID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nombre NVARCHAR2(50) NOT NULL
);

-- 5. Tabla de proveedores
CREATE TABLE Proveedores (
    ProveedorID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nombre NVARCHAR2(100) NOT NULL,
    Telefono NVARCHAR2(20),
    Direccion NVARCHAR2(150)
);

-- 6. Tabla de productos
CREATE TABLE Productos (
    ProductoID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nombre NVARCHAR2(100) NOT NULL,
    Precio NUMBER(10,2) NOT NULL,
    Stock NUMBER NOT NULL,
    CategoriaID NUMBER REFERENCES Categorias(CategoriaID),
    ProveedorID NUMBER REFERENCES Proveedores(ProveedorID)
);

-- 7. Tabla de inventario
CREATE TABLE Inventario (
    InventarioID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ProductoID NUMBER REFERENCES Productos(ProductoID),
    FechaMovimiento DATE DEFAULT SYSDATE,
    TipoMovimiento NVARCHAR2(20),
    Cantidad NUMBER,
    Observaciones NVARCHAR2(200)
);

-- 8. Tabla de ventas
CREATE TABLE Ventas (
    VentaID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ClienteID NUMBER REFERENCES Clientes(ClienteID),
    EmpleadoID NUMBER REFERENCES Empleados(EmpleadoID),
    FechaVenta DATE DEFAULT SYSDATE,
    Total NUMBER(10,2)
);

-- 9. Tabla de detalle de venta
CREATE TABLE DetalleVenta (
    DetalleID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    VentaID NUMBER REFERENCES Ventas(VentaID),
    ProductoID NUMBER REFERENCES Productos(ProductoID),
    Cantidad NUMBER NOT NULL,
    Subtotal NUMBER(10,2)
);

-- 10. Tabla de pedidos a proveedor
CREATE TABLE PedidosProveedor (
    PedidoID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ProveedorID NUMBER REFERENCES Proveedores(ProveedorID),
    FechaPedido DATE DEFAULT SYSDATE,
    Estado NVARCHAR2(20)
);

ALTER TABLE Inventario ADD PedidoID NUMBER REFERENCES PedidosProveedor(PedidoID);

-- Tablas Auxiliares
CREATE TABLE LogCambios (
    CambioID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Tabla NVARCHAR2(50),
    Descripcion NVARCHAR2(200),
    FechaCambio DATE DEFAULT SYSDATE
);

CREATE TABLE AuditoriaClientes (
    AuditoriaID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ClienteID NUMBER REFERENCES Clientes(ClienteID),
    FechaRegistro DATE DEFAULT SYSDATE
);
